### ISSUE TITLE
Can you add to documentation example how to call worker.stop() in "async pyzeebe 3.0.0"

### ISSUE THREAD

**Issue by tomas-zemres** [camunda-community-hub/zeebe-http-worker#147]
We are trying to use Zeebe 1.1.0 with pyzeebe 3.0.0rc3,

and we want to add signal handler on SIGTERM that calls worker.stop().
But we don't know how to correctly call "worker.stop()" that is "async def" from the signal handler.

Is it possible add simple example that uses "worker.stop()" to documentation for "async" pyzeebe 3.0.0, please?

**Comment by celanthe** [comment]
Hi @tomas-zemres! I noticed that you're using pyzeebe. You may want to also [open an issue](https://github.com/camunda-community-hub/pyzeebe/issues_) in that repository. The maintainer of pyzeebe, @JonatanMartens, is quite helpful and I'm sure would be happy to assist. :)

**Comment by tomas-zemres** [comment]
Sorry, I was posted the request to wrong repository, I reported it here https://github.com/camunda-community-hub/pyzeebe/issues/195
