### ISSUE TITLE
Decide whether we want to keep or remove Moustache support

### ISSUE THREAD

**Issue by pihme** [camunda-community-hub/zeebe-http-worker#210]
Currently this worker uses Moustache for templating. As part of the Connectors topic this approach was questioned. Overall sentiment seemed to be in favor of having templating done with FEEL expressions and using the engine to do it. 

At the same time, if the worker is used in a connector and corresponding element template, then this setup allows less flexibility to define in and output mappings. As far as I understand, the element template will add explicit input mappings for URL, method, etc. And because there is an explicit mapping, it doesn't simply copy all variables. So in essence the worker is called with only URL, method, etc. So there is nothing to run the template engine against

**Comment by pihme** [comment]
cc @saig0 @nikku

**Comment by nikku** [comment]
I think I got your point. It is a `A` or `B` decision, no `A+B`, essentially.

Read my thoughts [here](https://github.com/camunda/cloud-connectors/issues/10#issuecomment-1035983090).

**Comment by saig0** [comment]
> And because there is an explicit mapping, it doesn't simply copy all variables. So in essence the worker is called with only URL, method, etc.

No. The worker receives all variables independent if the task has variable input mappings or not.

**Comment by nikku** [comment]
Thanks for clarifying.
