### ISSUE TITLE
Grpc metadata

### ISSUE THREAD

**Issue by happwrap** [camunda-community-hub/zeebe-http-worker#292]
Hi! When calling the grpc-method "/gateway_protocol.Gateway/ActivateJobs" to the zeebe gateway, we need to add the type of task in the headers, for example: "job-type: http".
Does the current implementation allow this without fixing the java code and compiling?

**Comment by saig0** [comment]
@happwrap please describe your use case in more detail.

Do you use this Zeebe HTTP worker?
Which kind of header do you want to set? And why?
