### ISSUE TITLE
Retire this project in favor of official REST Connector

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/zeebe-http-worker#300]
Or at least link to https://docs.camunda.io/docs/next/components/connectors/out-of-the-box-connectors/rest/

**Comment by saig0** [comment]
I'm fine with recommending the official Camunda connector. :+1: 

If there is no further interest in this worker, I will mark it as [deprecated](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md#deprecated-).
