### ISSUE TITLE
Allow setting additional HTTP headers (e.g. api-key)

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/zeebe-http-worker#64]
In the earlier version of the cloud worker it was possible to set additonal http headers via the Zeebe Task Headers, e.g.

```
<bpmn:serviceTask id="ServiceTask_BookHotel" name="Book hotel">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="CAMUNDA-HTTP" retries="" />
        <zeebe:taskHeaders>
          <zeebe:header key="x-api-key" value="${aws-api-key}" />
          <zeebe:header key="url" value="${aws-lambda-base-url}/hotel/book" />
          <zeebe:header key="method" value="put" />
        </zeebe:taskHeaders>
      </bpmn:extensionElements>
 </bpmn:serviceTask>
```

This is not possible anymore with the current worker, but it makes a ton of sense to have it. It still need to be decided how exactly this is configured. I would probably simply propose a simple naming convention of the key, e.g. 'header-x-api-key', but haven't gave it another thought.

```
<bpmn:serviceTask id="ServiceTask_BookHotel" name="Book hotel">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="CAMUNDA-HTTP" retries="" />
        <zeebe:taskHeaders>
          <zeebe:header key="header-x-api-key" value="${aws-api-key}" />
          <zeebe:header key="url" value="${aws-lambda-base-url}/hotel/book" />
          <zeebe:header key="method" value="put" />
        </zeebe:taskHeaders>
      </bpmn:extensionElements>
 </bpmn:serviceTask>
```

**Comment by datakurre** [comment]
This would be nice. I was learning Camunda Cloud trial "out-of-the-box", and this became the first "blocker" to demo it without setting up custom workers.

**Comment by saig0** [comment]
To sum it up, we want to support arbitrary HTTP headers by using all custom headers/variables starting with the prefix `header-` as HTTP headers.

**Comment by saig0** [comment]
Done by #163 :rocket:
